import os
from time import sleep

white = '\u001b[47m \u001b[0m'
red = '\u001b[41m \u001b[0m'
blue = '\u001b[44m \u001b[0m'
green = '\u001b[42m \u001b[0m'
t = 0.15

os.system("cls")
print()
print()
print(' '*3 + blue*3 + ' '*9 + blue)
print(' '*3 + blue*3 + ' ' + red*2 + ' '*4 + white* 2 + blue)
print(' '*3 + blue*3 + ' ' + red*2 + ' '*4 + white* 2 + blue)
print(' '*4 + blue + ' ' + blue*2 + ' '*7 + blue)
print(' '*3 + blue*4 + ' '*8 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*2 + green*9)
print(' '*2 + green*16)
print(green*20)
sleep(1)
os.system("cls")

print()
print()
print(' '*3 + ' '*12 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*3 + blue*3 + red*2 + ' '*5 + white*2 + blue)
print(' '*3 + blue*3 + red*2 + ' '*7 + blue)
print(' '*4 + blue + ' ' + blue*2 + ' '*7 + blue)
print(' '*3 + blue*4 + ' '*8 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*2 + green*9)
print(' '*2 + green*16)
print(green*20)
sleep(t)
os.system("cls")

print()
print()
print(' '*3 + blue*3 + ' ' + red*2 + ' '*6 + blue)
print(' '*3 + blue*3 + ' ' + red*2 + ' '*4 + white* 2 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*4 + blue + ' '*2 + blue + ' '*7 + blue)
print(' '*3 + blue*5 + ' '*7 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*2 + green*9)
print(' '*2 + green*16)
print(green*20)
sleep(t)
os.system("cls")

print()
print(' '*8 + red*2)
print(' '*3 + blue*3 + ' '*2 + red*2 + ' '*5 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue*4 + ' '*8 + blue)
print(' '*3 + blue*2 + ' ' + blue*2 + ' '*7 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*2 + green*9)
print(' '*2 + green*16)
print(green*20)
sleep(t)
os.system("cls")

print(' '*9 + red*2)
print(' '*9 + red*2)
print(' '*3 + blue*3 + ' '*9 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue*3 + ' '*9 + blue)
print(' '*2 + blue*3 + ' ' + blue + ' '*8 + blue)
print(' '*4 + blue + ' ' + blue + ' '*8 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*2 + green*9)
print(' '*2 + green*16)
print(green*20)
sleep(t)
os.system("cls")

print(' '*10 + red*2)
print(' '*10 + red*2)
print(' '*3 + blue*3 + ' '*9 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue*3 + ' '*9 + blue)
print(' '*2 + blue + ' ' + blue + ' ' + blue + ' '*8 + blue)
print(' '*2 + blue + ' ' +  blue + ' ' + blue + ' '*8 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*2 + green*9)
print(' '*2 + green*16)
print(green*20)
sleep(t)
os.system("cls")

print(' '*11 + red*2)
print(' '*11 + red*2)
print(' '*3 + blue*3 + ' '*9 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue*3 + ' '*9 + blue)
print(' '*2 + blue + ' ' + blue + ' ' + blue + ' '*8 + blue)
print(' '*2 + blue + ' ' +  blue + ' ' + blue + ' '*8 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*2 + green*9)
print(' '*2 + green*16)
print(green*20)
sleep(t)
os.system("cls")

print()
print(' '*12 + red*2)
print(' '*3 + blue*3 + ' '*6 + red*2 + ' ' + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue*3 + ' '*9 + blue)
print(' '*2 + blue + ' ' + blue + ' ' + blue + ' '*8 + blue)
print(' '*2 + blue + ' ' +  blue + ' ' + blue + ' '*8 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*2 + green*9)
print(' '*2 + green*16)
print(green*20)
sleep(t)
os.system("cls")

print()
print()
print(' '*3 + blue*3 + ' '*7 + red* 2 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*3 + blue*3 + ' '*7 + white* 2 + blue)
print(' '*4 + blue + ' '*10 + blue)
print(' '*3 + blue*3 + ' '*9 + blue)
print(' '*2 + blue + ' ' + blue + ' ' + blue + ' '*8 + blue)
print(' '*2 + blue + ' ' +  blue + ' ' + blue + ' '*8 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*9 + blue)
print(' '*3 + blue + ' ' + blue + ' '*2 + green*9)
print(' '*2 + green*16)
print(green*20)

input()